### PR TITLE
eslintAndPrettierSetup

### PR DESCRIPTION
**Pull request by Laxmankohar**
image

image

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
Looks awesome👏, just one thing can you please make lint and prettier run on pre-commit so that formatting would be done on commiting the changes.

**Comment by Laxmankohar** [comment]
> Looks awesome👏, just one thing can you please make lint and prettier run on pre-commit so that formatting would be done on commiting the changes.

Bro, I was trying to make lint and prettier run on pre-commit but whole code get messed up. so, Merge this pull request sothat i can again fork the repo to start it again.

**Comment by Gaurav-Verma07** [comment]
hey I've merged your PR #21 in a new branch **task/eslint-pr-commit**. To fetch these changes you might need to re-fork the repo since you may only have **main branch** 

image

Your changes will be in this branch **task/eslint-pr-commit** only so make make sure to checkout to it.

Note: While merging your PR, I was facing merge conflicts, I resolved them but you please confirm that your changes are there.

**Comment by Gaurav-Verma07** [comment]
I've opened issue #24. Comment on it so that I can assign you.

**Comment by Laxmankohar** [comment]
> hey I've merged your PR #21 in a new branch **task/eslint-pr-commit**. To fetch these changes you might need to re-fork the repo since you may only have **main branch**
> 
> image
> 
> Your changes will be in this branch **task/eslint-pr-commit** only so make make sure to checkout to it.
> 
> Note: While merging your PR, I was facing merge conflicts, I resolved them but you please confirm that your changes are there.

Yes, My changes are there.

**Comment by Laxmankohar** [comment]
I am not able to fork it again. I think first of all i have to delete the already forked repo and try. Please confirm it. 

image

**Comment by Gaurav-Verma07** [comment]
Yes, first you need to delete your existing fork.

**Pull request closed without merging**
