### PR TITLE
Update the readme file

### PR DESCRIPTION
**Pull request by Code1705**
as required changes are made.

### CODE REVIEW

**Comment by Code1705** [comment]
@Gaurav-Verma07  I have committed the changes , please could you merge my PR?

**Comment by Gaurav-Verma07** [comment]
Hey, the way you customize **README.md** is quite appreciable.
But there's two changes I'd suggest :
1. The distance between list numbers and and content is quite much. Look into this and better change it into an unordered list.

image

2. The contribution guidelines are already there in **CONTRIBUTING.md**. Adding them in README.md makes it look a bit messy so I would suggest you to remove them or you can propose your own idea.

**Comment by Gaurav-Verma07** [comment]
Also this line in particular, I'm not getting what you're trying to express here. 
Might be a grammatical issue.
Please look into this.

image

**Comment by Code1705** [comment]
Ok sure.

**Comment by Code1705** [comment]
@Gaurav-Verma07  as per told by you I made the necessary changes , please could you merge my pr with proper label and JWOC tag?

**Comment by Gaurav-Verma07** [comment]
@Code1705 Thanks for the changes. I'll merge by EOD

**Comment by Gaurav-Verma07** [comment]
Hey, I cannot completely merge your PR, the code is poorly customized. 

image

image

So I'm merging only this section so that you get reward for your work:

image

**Comment by Gaurav-Verma07** [comment]
Please add your contribution info in **.all-contributorsrc**  and **README.md**

**Pull request merged**
