### PR TITLE
Run eslint and prettier on pre-commit

### PR DESCRIPTION
**Pull request by Laxmankohar**

### CODE REVIEW

**Comment by Gaurav-Verma07** [comment]
Hey, it seems husky not running on pre-commit. It might not be configured yet. 
Take a look.

image

**Comment by Laxmankohar** [comment]
> Hey, it seems husky not running on pre-commit. It might not be configured yet. Take a look.
> 
> image

its working in my system.

image

**Comment by Laxmankohar** [comment]
I hope it was not a problem of branch.

**Comment by Gaurav-Verma07** [comment]
Okay, seems some bug from my side.
I'll merge once I verify from my side.

**Comment by Laxmankohar** [comment]
> Okay, seems some bug from my side. I'll merge once I verify from my side.

ok.

**Pull request merged**
